/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkidgraphRouteImport } from './routes/skidgraph'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkidgraphIndexRouteImport } from './routes/skidgraph.index'
import { Route as InvestigationsIndexRouteImport } from './routes/investigations.index'
import { Route as SkidgraphGraphIdRouteImport } from './routes/skidgraph.$graphId'
import { Route as LegalDocRouteImport } from './routes/legal.$doc'
import { Route as InvestigationsCaseIdRouteImport } from './routes/investigations.$caseId'

const SkidgraphRoute = SkidgraphRouteImport.update({
  id: '/skidgraph',
  path: '/skidgraph',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkidgraphIndexRoute = SkidgraphIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SkidgraphRoute,
} as any)
const InvestigationsIndexRoute = InvestigationsIndexRouteImport.update({
  id: '/investigations/',
  path: '/investigations/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkidgraphGraphIdRoute = SkidgraphGraphIdRouteImport.update({
  id: '/$graphId',
  path: '/$graphId',
  getParentRoute: () => SkidgraphRoute,
} as any)
const LegalDocRoute = LegalDocRouteImport.update({
  id: '/legal/$doc',
  path: '/legal/$doc',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsCaseIdRoute = InvestigationsCaseIdRouteImport.update({
  id: '/investigations/$caseId',
  path: '/investigations/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skidgraph': typeof SkidgraphRouteWithChildren
  '/investigations/$caseId': typeof InvestigationsCaseIdRoute
  '/legal/$doc': typeof LegalDocRoute
  '/skidgraph/$graphId': typeof SkidgraphGraphIdRoute
  '/investigations/': typeof InvestigationsIndexRoute
  '/skidgraph/': typeof SkidgraphIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/investigations/$caseId': typeof InvestigationsCaseIdRoute
  '/legal/$doc': typeof LegalDocRoute
  '/skidgraph/$graphId': typeof SkidgraphGraphIdRoute
  '/investigations': typeof InvestigationsIndexRoute
  '/skidgraph': typeof SkidgraphIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skidgraph': typeof SkidgraphRouteWithChildren
  '/investigations/$caseId': typeof InvestigationsCaseIdRoute
  '/legal/$doc': typeof LegalDocRoute
  '/skidgraph/$graphId': typeof SkidgraphGraphIdRoute
  '/investigations/': typeof InvestigationsIndexRoute
  '/skidgraph/': typeof SkidgraphIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/chat'
    | '/dashboard'
    | '/settings'
    | '/sitemap.xml'
    | '/skidgraph'
    | '/investigations/$caseId'
    | '/legal/$doc'
    | '/skidgraph/$graphId'
    | '/investigations/'
    | '/skidgraph/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/chat'
    | '/dashboard'
    | '/settings'
    | '/sitemap.xml'
    | '/investigations/$caseId'
    | '/legal/$doc'
    | '/skidgraph/$graphId'
    | '/investigations'
    | '/skidgraph'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/chat'
    | '/dashboard'
    | '/settings'
    | '/sitemap.xml'
    | '/skidgraph'
    | '/investigations/$caseId'
    | '/legal/$doc'
    | '/skidgraph/$graphId'
    | '/investigations/'
    | '/skidgraph/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SkidgraphRoute: typeof SkidgraphRouteWithChildren
  InvestigationsCaseIdRoute: typeof InvestigationsCaseIdRoute
  LegalDocRoute: typeof LegalDocRoute
  InvestigationsIndexRoute: typeof InvestigationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skidgraph': {
      id: '/skidgraph'
      path: '/skidgraph'
      fullPath: '/skidgraph'
      preLoaderRoute: typeof SkidgraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skidgraph/': {
      id: '/skidgraph/'
      path: '/'
      fullPath: '/skidgraph/'
      preLoaderRoute: typeof SkidgraphIndexRouteImport
      parentRoute: typeof SkidgraphRoute
    }
    '/investigations/': {
      id: '/investigations/'
      path: '/investigations'
      fullPath: '/investigations/'
      preLoaderRoute: typeof InvestigationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skidgraph/$graphId': {
      id: '/skidgraph/$graphId'
      path: '/$graphId'
      fullPath: '/skidgraph/$graphId'
      preLoaderRoute: typeof SkidgraphGraphIdRouteImport
      parentRoute: typeof SkidgraphRoute
    }
    '/legal/$doc': {
      id: '/legal/$doc'
      path: '/legal/$doc'
      fullPath: '/legal/$doc'
      preLoaderRoute: typeof LegalDocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations/$caseId': {
      id: '/investigations/$caseId'
      path: '/investigations/$caseId'
      fullPath: '/investigations/$caseId'
      preLoaderRoute: typeof InvestigationsCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SkidgraphRouteChildren {
  SkidgraphGraphIdRoute: typeof SkidgraphGraphIdRoute
  SkidgraphIndexRoute: typeof SkidgraphIndexRoute
}

const SkidgraphRouteChildren: SkidgraphRouteChildren = {
  SkidgraphGraphIdRoute: SkidgraphGraphIdRoute,
  SkidgraphIndexRoute: SkidgraphIndexRoute,
}

const SkidgraphRouteWithChildren = SkidgraphRoute._addFileChildren(
  SkidgraphRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SkidgraphRoute: SkidgraphRouteWithChildren,
  InvestigationsCaseIdRoute: InvestigationsCaseIdRoute,
  LegalDocRoute: LegalDocRoute,
  InvestigationsIndexRoute: InvestigationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
